### ISSUE TITLE
Cannot use subclass to PROV-O classes

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#22]
The PROV-O classes in SBOL are not currently usable as superclasses in SBOL factory.
For example: 
```
paml:BehaviorExecution rdf:type owl:Class ;
        rdfs:comment "Record of the operation of a UML Behavior, real or simulated" ;
        rdfs:subClassOf prov:Activity .
```
results in: `Exception: http://bioprotocols.org/paml#BehaviorExecution has no superclass`

**Comment by bbartley** [comment]
Unfortunately, PROV-O classes are not defined in the SBOL-OWL turtle file, so sbol_factory is unaware of their existence.

**Comment by jakebeal** [comment]
I think we need a way to figure out how to deal with this. It's slightly problematic because SBOL's usage of PROV-O is not identical to the original PROV-O definitions.

**Comment by bbartley** [comment]
The bug as noted originates in the `query_required_properties` method.  This method is used to infer and generate a constructor signature.  Currently this cannot be done for PROV-O classes because the ontology is not included in SBOLFactory, and, even if it were, PROV-O does not restrict property cardinalities.  Therefore, we have to hard-code handling of these classes.

**Comment by bbartley** [comment]
It wil also be a problem if we ever need to extend OM classes as well.
