### ISSUE TITLE
sbol_factory doesn't confuses classes with the same name in different namespaces

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#23]
When I put in place a patch to allow sbol_factory to work around #22, I ran into a new issue: even though I specified prov:Activity as the superclass, I ended up with a class that inherits from uml:Activity.

**Comment by bbartley** [comment]
There is a naming collision here, as sbol_factory is trying to generate two different `Activity` classes in the same namespace.  Perhaps the easiest workaround is to alias one of them as `UMLActivity`.  A more satisfactory alternative would be to create a unique module namespace for each ontology based on its qname prefix, so we would get `uml.Activity` and `provo.Activity`.  I don't immediately know how to implement that with Python, or even know if it is possible, but it is probably worth investigating.

**Comment by jakebeal** [comment]
The names the classes are getting aren't actually the ones that they start with in any case (e.g., `uml.Activity` is `<class 'sbol_factory.sbol_factory.Activity'>`), so perhaps they could be given a "full name" based on the package?

That way you'd start with a name guaranteed to be unique, such as `sbol_factory.sbol_factory.uml_Activity`.  Then the "short name" renaming would happen when it actually gets remapped/imported into the `uml` module.

**Comment by bbartley** [comment]
I believe I have a solution that generates classes for each ontology in its own module namespace.

However, the test ontology is currently failing because multiple inheritance is not supported: `uml:Activity` is derived from `prov:Activity` and `uml:Behavior`.  This error due to multiple inheritance wasn't occurring before.  I'm not sure if I introduced this error as a side effect of the other changes.

**Comment by jakebeal** [comment]
I think this is an error in your code, since uml:Activity is not derived from prov:Activity
